version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/aashiyanahub
      - JWT_SECRET=39a6e7e793ff847b25e3bf07e0d8606fe988879b4dd0e6a53e22805e1577589e
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - CLOUDINARY_CLOUD_NAME=dpsn5e0nd
      - CLOUDINARY_API_KEY=964193625613431
      - CLOUDINARY_API_SECRET=upnLSa-uUYmyIYCSZXQK_CEw-os
    depends_on:
      - mongo
      - elasticsearch

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  mongodb_data:
  es_data: